---
version: "3"

services:
  ceos-2:
    hostname: ceos-2
    image: "ceos:4.25.6M"
    privileged: true
    environment:
      CEOS: 1
      INTFTYPE: eth
      ETBA: 1
      SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT: 1
      EOS_PLATFORM: ceoslab
      container: docker
    command:
      - "/sbin/init"
      - "systemd.setenv=INTFTYPE=eth"
      - "systemd.setenv=ETBA=1"
      - "systemd.setenv=SKIP_ZEROTOUCH_BARRIER_IN_SYSDBINIT=1"
      - "systemd.setenv=CEOS=1"
      - "systemd.setenv=EOS_PLATFORM=ceoslab"
      - "systemd.setenv=container=docker"
    networks:
      default:
      net1:

networks:
  net1:
